### ISSUE TITLE
std::bad_alloc on empty pardefs

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#31] opened 2018-10-01 12:04 UTC
See https://github.com/apertium/apertium-nob/commit/51f51ae797a57d24f47184fcf8f5dd5923eb602a
```
<pardef n="RL_s_case">
  <e>       <p><l></l>          <r></r></p></e>
  <e r="RL"><p><l>s</l>         <r><s n="gen"/></r></p></e>
</pardef>
```
creates a std::bad_alloc when trying to analyse something using this pardef.

The workaround is to add an entry that never matches, but this really should be fixed in lt-comp.

**Comment by TinoDidriksen** [comment] 2018-10-04 09:19
What is the minimal testcase for triggering bad_alloc? I tried a few things, but couldn't.

**Comment by unhammer** [comment] 2018-10-05 08:57
```
$ lt-comp lr alloc.dix alloc.bin && echo a|lt-proc  alloc.bin
main@standard 2 2
std::bad_alloc$
$ cat alloc.dix 
```

```
<?xml version="1.0" encoding="UTF-8"?>
<dictionary>

  <alphabet/>

  <sdefs>
    <sdef n="det"/>
    <sdef n="gen"/>
  </sdefs>

  <pardefs>

    <pardef n="RL_s_case">
      <!-- The fallthrough: -->
      <e>       <p><l></l>          <r></r></p></e>
      <!-- Workaround: uncomment the following: -->
      <!-- <e>       <p><l>AVOID_STD_BAD_ALLOC_HACK</l>          <r>AVOID_STD_BAD_ALLOC_HACK</r></p></e> -->
      <!-- The RL entry isn't necessary to reproduce, but it's in this kind of pardef (RL + fallthrough) we tend to see the issue: -->
      <e r="RL"><p><l>s</l>         <r><s n="gen"/></r></p></e>
    </pardef>

    <pardef n="pd1" c="If we remove this pardef and the det-tag on the section entry instead,
                       lt-proc notices and says
                       Error: Invalid dictionary (hint: the left side of an entry is empty)">
      <e>       <p><l></l>        <r><s n="det"/></r></p><par n="RL_s_case"/></e>
    </pardef>

  </pardefs>

  <section id="main" type="standard">
    <e lm="a">       <i>a</i><par n="pd1"/></e>
  </section>
</dictionary>
```

**Comment by mr-martian** [comment] 2022-03-14 21:40
Unable to reproduce.

I think this was caused by a bug in `Transducer::insertTransducer()` which was fixed in https://github.com/apertium/lttoolbox/commit/ed3551232f016f8d94afc094fa8bfded422cc3b7

**Closed by mr-martian** 2022-03-14 21:40 UTC
