### ISSUE TITLE
Apertium is not translating a Word document

### ISSUE THREAD

**Issue by Elivica** [apertium/lttoolbox#122] opened 2021-05-22 16:44 UTC
Hi.    I´m trying to translate a Word document (Office95 version) from Spanish into Valencian and it only works on the first paragraphs, the rest of the document is left untransalated.  It works perfectly when transalated from Spanish into English, though.
[T6 Algebra castellano.docx](https://github.com/apertium/apertium/files/6526805/T6.Algebra.castellano.docx)

**Comment by TinoDidriksen** [comment] 2021-09-27 13:23
So likely something to do with empty or all-whitespace segments. Still an lttoolbox issue, hence why I unassigned myself. Pinging @khannatanmai

**Comment by unhammer** [comment] 2021-09-30 08:51
Was this the one that turned out to be in `lt-proc -x`?

**Comment by xavivars** [comment] 2021-09-30 08:55
Yes. I still think it's probably worth to try to fix it, or (as soon as I move apertium-cat related pairs out of it) deprecate that functionality. Because having a not-always-working module in the pipeline seems wrong.

**Comment by unhammer** [comment] 2022-06-07 08:01
Perhaps #144 fixes this

**Comment by mr-martian** [comment] 2022-06-29 19:20
I am unable to reproduce this based on @xavivars's example, so it might have been fixed in #149, but I also failed to reproduce it on aa1cf3a506b672d82db52d0f57698d1b5ccd389b, so maybe something else fixed (or -cat has changed).

**Comment by xavivars** [comment] 2022-06-29 20:33
-cat moved away from using intergen some of months ago, when we moved that to preferences using cg

**Comment by mr-martian** [comment] 2022-07-23 14:29
The original error was due to an invalid index being passed to `substr()`. The relevant call was removed in one of the rewrites, so I am marking this as completed.

**Closed by mr-martian** 2022-07-23 14:29 UTC

**Comment by Elivica** [comment] 2022-07-23 17:10
Thank you for all the work you all have developed during such a long
period!
